#!/usr/bin/env bash
# =============================================================================
# scripts/bootstrap.sh
# One-time setup: creates Azure Blob Storage backend for Terraform remote state.
# Run this BEFORE any "terraform init".
# =============================================================================

set -euo pipefail

RESOURCE_GROUP="rg-tfstate"
LOCATION="eastus"
STORAGE_ACCOUNT="tfstate$(cat /dev/urandom | tr -dc 'a-z0-9' | head -c 8)"
CONTAINER="tfstate"

echo "==> Checking prerequisites..."
command -v az       >/dev/null 2>&1 || { echo "ERROR: Azure CLI not installed."; exit 1; }
command -v terraform>/dev/null 2>&1 || { echo "ERROR: Terraform not installed."; exit 1; }
az account show --output none 2>/dev/null || { echo "ERROR: Run 'az login' first."; exit 1; }

echo "    Logged in : $(az account show --query user.name -o tsv)"
echo "    Subscription: $(az account show --query name -o tsv)"
echo ""

echo "==> Creating resource group: $RESOURCE_GROUP..."
az group create \
  --name "$RESOURCE_GROUP" \
  --location "$LOCATION" \
  --output none
echo "    ✓ Resource group ready"

echo "==> Creating storage account: $STORAGE_ACCOUNT..."
az storage account create \
  --name "$STORAGE_ACCOUNT" \
  --resource-group "$RESOURCE_GROUP" \
  --location "$LOCATION" \
  --sku Standard_LRS \
  --kind StorageV2 \
  --allow-blob-public-access false \
  --min-tls-version TLS1_2 \
  --output none
echo "    ✓ Storage account ready"

echo "==> Enabling blob versioning (for state rollback)..."
az storage account blob-service-properties update \
  --account-name "$STORAGE_ACCOUNT" \
  --resource-group "$RESOURCE_GROUP" \
  --enable-versioning true \
  --output none
echo "    ✓ Versioning enabled"

echo "==> Creating blob container: $CONTAINER..."
az storage container create \
  --name "$CONTAINER" \
  --account-name "$STORAGE_ACCOUNT" \
  --auth-mode login \
  --output none
echo "    ✓ Container ready"

# Save for reference (file is gitignored)
cat > .backend-config.txt << CONF
# Generated by bootstrap.sh on $(date)
# DO NOT COMMIT THIS FILE
resource_group_name  = "$RESOURCE_GROUP"
storage_account_name = "$STORAGE_ACCOUNT"
container_name       = "$CONTAINER"
CONF

echo ""
echo "============================================================"
echo " BOOTSTRAP COMPLETE"
echo "============================================================"
echo " Resource Group  : $RESOURCE_GROUP"
echo " Storage Account : $STORAGE_ACCOUNT"
echo " Container       : $CONTAINER"
echo " Location        : $LOCATION"
echo ""
echo " NEXT STEP: Replace REPLACE_WITH_STORAGE_ACCOUNT in:"
echo "   environments/dev/backend.tf"
echo "   environments/prod/backend.tf"
echo " with: $STORAGE_ACCOUNT"
echo "============================================================"
